#!/usr/bin/env python3
"""Build deterministic standalone installer assets from the checked-out source."""
import argparse
import base64
import gzip
import hashlib
import io
from pathlib import Path
import re
import shutil
import tarfile

ROOT = Path(__file__).resolve().parents[1]


def build_installer():
    version = (ROOT / 'VERSION').read_text().strip()
    if not re.fullmatch(r'[0-9]+\.[0-9]+\.[0-9]+', version):
        raise SystemExit('VERSION must contain a numeric major.minor.patch version')
    names = ['install.sh', 'restore.py', 'README.md', 'VERSION', 'CHANGELOG.md', 'test-results.log']
    for directory in ('src', 'tests', 'scripts', 'docs'):
        for path in sorted((ROOT / directory).rglob('*')):
            if path.is_file() and '__pycache__' not in path.parts and path.suffix != '.pyc':
                if path.is_symlink():
                    raise SystemExit(f'Refusing symlink in payload: {path}')
                names.append(path.relative_to(ROOT).as_posix())
    raw = io.BytesIO()
    with tarfile.open(fileobj=raw, mode='w', format=tarfile.PAX_FORMAT) as archive:
        for name in sorted(names):
            data = (ROOT / name).read_bytes()
            info = tarfile.TarInfo(name)
            info.size = len(data)
            info.mode = 0o755 if name.endswith('.sh') else 0o644
            info.uid = info.gid = info.mtime = 0
            archive.addfile(info, io.BytesIO(data))
    compressed = io.BytesIO()
    with gzip.GzipFile(filename='', mode='wb', fileobj=compressed, mtime=0) as stream:
        stream.write(raw.getvalue())
    payload = compressed.getvalue()
    digest = hashlib.sha256(payload).hexdigest()
    header = '''#!/bin/bash
# MobileUSB VERSION upgrade. Generated by scripts/build_release.py; edit source instead.
set -Eeuo pipefail
TEMP=$(mktemp -d)
trap 'rm -rf -- "$TEMP"' EXIT
awk 'seen { print } /^__MOBILEUSB_PAYLOAD__$/ { seen=1 }' "$0" | base64 -d > "$TEMP/payload.tar.gz"
printf '%s  %s\\n' 'DIGEST' "$TEMP/payload.tar.gz" | sha256sum --check --status
if [ "${1:-}" = '--extract' ]; then
    DEST=${2:?Supply a destination directory}
    mkdir -p -- "$DEST"
    tar --no-same-owner -xzf "$TEMP/payload.tar.gz" -C "$DEST"
    printf 'Source extracted to %s\\n' "$DEST"
    exit 0
fi
tar --no-same-owner -xzf "$TEMP/payload.tar.gz" -C "$TEMP"
bash "$TEMP/install.sh" "$@"
exit 0
__MOBILEUSB_PAYLOAD__
'''.replace('VERSION', version).replace('DIGEST', digest)
    return header.encode() + base64.encodebytes(payload)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--update-tracked', action='store_true', help='Also replace the tracked standalone installer')
    parser.add_argument('--check', action='store_true', help='Fail if the tracked installer differs from its source')
    args = parser.parse_args()
    if args.check and args.update_tracked:
        parser.error('Choose --check or --update-tracked, not both')
    installer = build_installer()
    tracked = ROOT / 'mobileusb-upgrade.sh'
    if args.check:
        if tracked.read_bytes() != installer:
            raise SystemExit('Tracked installer is stale. Run scripts/build_release.py --update-tracked')
        print('PASS: tracked installer exactly matches reproducible source payload')
        return
    out = ROOT / 'dist'
    out.mkdir(exist_ok=True)
    (out / 'mobileusb-upgrade.sh').write_bytes(installer)
    shutil.copyfile(ROOT / 'scripts/fix-web-storage.sh', out / 'mobileusb-fix-web-storage.sh')
    assets = ('mobileusb-upgrade.sh', 'mobileusb-fix-web-storage.sh')
    for name in assets:
        (out / name).chmod(0o755)
    (out / 'SHA256SUMS').write_text(''.join(f'{hashlib.sha256((out/name).read_bytes()).hexdigest()}  {name}\n' for name in assets))
    if args.update_tracked:
        tracked.write_bytes(installer)
        tracked.chmod(0o755)
    print(f'Built {len(assets)} installer assets and SHA256SUMS in {out}')


if __name__ == '__main__':
    main()
